substitutions:
  device_name: garage_door #change
  friendly_name: Garage Door #change
  icon: "mdi:light-switch"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp12e #esp01_1m if module is flashable

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret ap_pass

captive_portal:

# Standard Information
web_server:
  port: 80

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime

  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    ssid:
      name: ${friendly_name} Connected SSID
    bssid:
      name: ${friendly_name} Connected BSSID
    mac_address:
      name: ${friendly_name} Mac Wifi Address

binary_sensor:

switch:
- platform: gpio
  id: relay_${device_name}
  pin:
    number: GPIO5
  restore_mode: RESTORE_DEFAULT_OFF
  internal: True

- platform: restart
  name: ${friendly_name} Restart

- platform: template
  name: ${friendly_name}
  id: ${device_name}
  icon: ${icon}
  turn_on_action:
    - switch.turn_on: relay_${device_name}
  turn_off_action:
    - switch.turn_off: relay_${device_name}